#!/usr/bin/with-contenv bash

exec \
  s6-setuidgid ali \
    /opt/code-server/code-server \
      --auth none \
      --cert /opt/filer/os/acme/'*.home.mustakim.com'/'*.home.mustakim.com.cer' \
      --cert-key /opt/filer/os/acme/'*.home.mustakim.com'/'*.home.mustakim.com.key' \
      --disable-telemetry \
      --disable-updates \
      --extensions-dir /home/ali/.code-server/extensions \
      --extra-builtin-extensions-dir /opt/code-extensions/ \
      --host 0.0.0.0 \
      --port 8080 \
      --user-data-dir /home/ali/.code-server/data \
      /home/ali
