#!/usr/bin/with-contenv bash

exec \
  s6-setuidgid ali \
    /opt/code-server/code-server \
      --host 0.0.0.0 \
      --port 8443 \
      --user-data-dir /home/ali/.code-server/data \
      --extensions-dir /home/ali/.code-server/extensions \
      --extra-builtin-extensions-dir /opt/code-extensions/ \
      --disable-ssh \
      --disable-telemetry \
      --disable-updates \
      --auth none \
      /home/ali
