version: 2.1

jobs:
  build_one:
    working_directory: /app
    docker:
      - image: circleci/golang
        user: root
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build and push to docker
          command: |
            mkdir -p /go/src/github.com/forwardcomputers
            mv -f /app /go/src/github.com/forwardcomputers/${CIRCLE_PROJECT_REPONAME}
            echo "USER=root" >> $BASH_ENV
            echo "export CIRCLE_WORKING_DIRECTORY=/go/src/github.com/forwardcomputers/${CIRCLE_PROJECT_REPONAME}" >> $BASH_ENV
            source $BASH_ENV
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            GH_SHA=$( \docker log 
              curl --silent --location --url https://api.github.com/repos/forwardcomputers/dockerfiles/commits | \
              jq -r '.[0].sha' \
            )
            GH_APP=( $( \
              curl --silent --location --url https://api.github.com/repos/forwardcomputers/dockerfiles/commits/"${GH_SHA}" | \
              jq --raw-output '[.files | .[] | select( .status == "added" or .status == "modified" and ( .filename | contains(".circleci") | not ) and ( .filename | contains("/") ) ) | .filename | split("/")[0]] | unique[]') \
            )
            for APP in "${GH_APP[@]}"; do
              ./dapp.sh upgrade ${APP}
            done

  build_all:
    working_directory: /app
    docker:
      - image: circleci/golang
        user: root
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build and push to docker
          command: |
            mkdir -p /go/src/github.com/forwardcomputers
            mv -f /app /go/src/github.com/forwardcomputers/${CIRCLE_PROJECT_REPONAME}
            echo "USER=root" >> $BASH_ENV
            echo "export CIRCLE_WORKING_DIRECTORY=/go/src/github.com/forwardcomputers/${CIRCLE_PROJECT_REPONAME}" >> $BASH_ENV
            source $BASH_ENV
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            ./dapp.sh upgrade_all

workflows:
  version: 2.1

  commit:
    jobs:
      - build_one:
          context: global

  nightly:
    triggers:
      - schedule:
          # Times are in UTC, this job is run
          # daily @ 14HRS = 9AM EST, 20HRS = 3PM EST
          # cron: "0 14,20 * * *"
          cron: "26 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_all:
          context: global
